<!-- Tabela User -->
CREATE TABLE `Usrk` (
	`USR_AIC` INT UNSIGNED NOT NULL AUTO_INCREMENT
	`USR_EML` VARCHAR(50) NOT NULL,
	`USR_PASS` VARCHAR(50) NOT NULL,
	`USR_CPF` VARCHAR(50) NOT NULL,
	`USR_NM` INT NOT NULL,
	PRIMARY KEY (`USR_AIC`)
	ALTER TABLE `usrk`
	CHANGE COLUMN `USR_NM` `USR_NM` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `USR_CPF`;
	ALTER TABLE `usrk`
	CHANGE COLUMN `USR_EML` `USR_EML` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_0900_ai_ci' AFTER `USR_AIC`,
	CHANGE COLUMN `USR_CPF` `USR_CPF` VARCHAR(50) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_0900_ai_ci' AFTER `USR_PASS`;


)
COLLATE='utf8mb4_0900_ai_ci'
;

CREATE TABLE `etg` (
	`ETG_AIC` INT UNSIGNED NOT NULL,
	`USR_AIC` INT UNSIGNED NOT NULL,
	`ETG_DTET` INT NULL,
	`ETG_HRET` INT NULL,
	`ETG_DEST` INT NOT NULL,
	`ETG_SATUS` INT NOT NULL,
	PRIMARY KEY (`ETG_AIC`) USING BTREE,
	INDEX `FK_USR_AIC` (`USR_AIC`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

ALTER TABLE `etg`
	CHANGE COLUMN `ETG_DTET` `ETG_DTET` DATE NULL AFTER `USR_AIC`,
	CHANGE COLUMN `ETG_HRET` `ETG_HRET` TIME NULL AFTER `ETG_DTET`,
	CHANGE COLUMN `ETG_DEST` `ETG_DEST` VARCHAR() NOT NULL DEFAULT '' AFTER `ETG_HRET`,
	CHANGE COLUMN `ETG_SATUS` `ETG_SATUS` TINYINT NOT NULL DEFAULT (0) AFTER `ETG_DEST`;


	ALTER TABLE `etg`
	ADD COLUMN `ETG_DTRGS` DATE NOT NULL AFTER `ETG_SATUS`,
	ADD COLUMN `ETG_HRRGS` TIME NOT NULL AFTER `ETG_DTRGS`;

	CREATE TABLE `crg` (
	`CRG_AIC` INT UNSIGNED NOT NULL,
	`CRG_DESC` VARCHAR() NOT NULL DEFAULT '',
	`CRG_REM` VARCHAR() NOT NULL DEFAULT '',
	`CRG_QNT` VARCHAR() NOT NULL DEFAULT '',
	PRIMARY KEY (`CRG_AIC`)
)
COLLATE='utf8mb4_0900_ai_ci'
;

CREATE TABLE `cmho` (
	`CMHO_AIC` INT UNSIGNED NOT NULL,
	`CMHO_PLA` INT NOT NULL,
	`CMHO_MDL` VARCHAR(50) NOT NULL DEFAULT '',
	`USR_AIC` INT UNSIGNED NOT NULL DEFAULT (0),
	PRIMARY KEY (`CMHO_AIC`),
	INDEX `Index 2` (`USR_AIC`)
)
COLLATE='utf8mb4_0900_ai_ci'
;

ALTER TABLE `etg`
	ADD COLUMN `CMHO_AIC` INT NULL AFTER `ETG_HRRGS`;

	ALTER TABLE `etg`
	CHANGE COLUMN `CMHO_AIC` `CMHO_AIC` INT UNSIGNED NOT NULL AFTER `ETG_HRRGS`;

	ALTER TABLE `etg`
	CHANGE COLUMN `CMHO_AIC` `CMHO_AIC` INT UNSIGNED NOT NULL AFTER `ETG_HRRGS`,
	ADD INDEX `FK_CMHO_AIC` (`CMHO_AIC`);

	ALTER TABLE `usrk`
	CHANGE COLUMN `USR_AIC` `USR_AIC` INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `USR_EML` `USR_EML` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci' AFTER `USR_AIC`,
	CHANGE COLUMN `USR_CPF` `USR_CPF` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci' AFTER `USR_PASS`,
	CHANGE COLUMN `USR_NM` `USR_NM` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci' AFTER `USR_CPF`;

