CREATE TABLE `usr` (
	`USR_AIC` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`USR_AIC`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE `etg` (
	`ETG_AIC` INT UNSIGNED NOT NULL,
	`USR_AIC` INT UNSIGNED NOT NULL,
	`ETG_DTET` INT NULL,
	`ETG_HRET` INT NULL,
	`ETG_DEST` INT NOT NULL,
	`ETG_SATUS` INT NOT NULL,
	PRIMARY KEY (`ETG_AIC`) USING BTREE,
	INDEX `FK_USR_AIC` (`USR_AIC`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

ALTER TABLE `etg`
	CHANGE COLUMN `ETG_DTET` `ETG_DTET` DATE NULL AFTER `USR_AIC`,
	CHANGE COLUMN `ETG_HRET` `ETG_HRET` TIME NULL AFTER `ETG_DTET`,
	CHANGE COLUMN `ETG_DEST` `ETG_DEST` VARCHAR() NOT NULL DEFAULT '' AFTER `ETG_HRET`,
	CHANGE COLUMN `ETG_SATUS` `ETG_SATUS` TINYINT NOT NULL DEFAULT (0) AFTER `ETG_DEST`;
